version: '3'

services:
  matomo-app:
    image: docker.io/matomo:fpm-alpine
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    environment:
      MATOMO_DATABASE_ADAPTER: ${MATOMO_DATABASE_ADAPTER}
      MATOMO_DATABASE_DBNAME: ${MATOMO_DATABASE_DBNAME}
      MATOMO_DATABASE_HOST: ${MATOMO_DATABASE_HOST}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MATOMO_DATABASE_TABLES_PREFIX: ${MATOMO_DATABASE_TABLES_PREFIX}
      MATOMO_DATABASE_USERNAME: ${MATOMO_DATABASE_USERNAME}
    networks:
      - default

  matomo-web:
    image: docker.io/nginx:alpine
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - matomo-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo.entrypoints=websecure"
      - "traefik.http.routers.matomo.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.matomo.tls=true"
      - "traefik.http.routers.matomo.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.matomo.service=matomo"
      - "traefik.http.services.matomo.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
