apiVersion: v1
kind: Secret
metadata:
  name: adhocracy
type: Opaque
data:
  SECRET_KEY: c2hvdWxkLWJlLXNvbWUtcmFuZG9tLXN0cmluZw==
  EMAIL_HOST_PASSWORD: c29tZS1zZWNyZXQtcHc=
  EMAIL_HOST_USER: YWNjb3VudEBleGFtcGxlLmNvbQ==
immutable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adhocracy
data:
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp.example.com"
  EMAIL_PORT: "465"
  EMAIL_SUBJECT_PREFIX: "[Adhocracy]"
  EMAIL_TIMEOUT: "None"
  EMAIL_USE_LOCALTIME: "False"
  EMAIL_USE_SSL: "True"
  EMAIL_USE_TLS: "False"
  SERVER_EMAIL: "mailbot@example.com"
  DEFAULT_FROM_EMAIL: "mailbot@example.com"
immutable: true
---
apiVersion: v1
kind: Pod
metadata:
  name: adhocracy
  labels:
    app: adhocracy
spec:
  containers:
    - name: web
      image: schmidtdenktmit/adhocracyplus:2202.02
      ports:
        - name: http
          protocol: TCP
          containerPort: 8000
      env:
        # Config values outlined in example.env
        - name: EMAIL_BACKEND
          valueFrom:
            configMapKeyRef:
              name: adhocracy
              key: EMAIL_BACKEND
        - name: EMAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: adhocracy
              key: EMAIL_HOST
        - name: EMAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: adhocracy
              key: EMAIL_PORT
        - name: EMAIL_SUBJECT_PREFIX
          valueFrom:
            configMapKeyRef:
              name: adhocracy
              key: EMAIL_SUBJECT_PREFIX
        - name: EMAIL_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: adhocracy
              key: EMAIL_TIMEOUT
        - name: EMAIL_USE_LOCALTIME
          valueFrom:
            configMapKeyRef:
              name: adhocracy
              key: EMAIL_USE_LOCALTIME
        - name: EMAIL_USE_SSL
          valueFrom:
            configMapKeyRef:
              name: adhocracy
              key: EMAIL_USE_SSL
        - name: EMAIL_USE_TLS
          valueFrom:
            configMapKeyRef:
              name: adhocracy
              key: EMAIL_USE_TLS
        - name: SERVER_EMAIL
          valueFrom:
            configMapKeyRef:
              name: adhocracy
              key: SERVER_EMAIL
        - name: DEFAULT_FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: adhocracy
              key: DEFAULT_FROM_EMAIL
        # Secret values outlined in example.env
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: adhocracy
              key: SECRET_KEY
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adhocracy
              key: EMAIL_HOST_PASSWORD
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: adhocracy
              key: EMAIL_HOST_USER
---
apiVersion: v1
kind: Service
metadata:
  name: adhocracy
spec:
  selector:
    app: adhocracy
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000