version: '3.8'

services:
  hello:
    image: docker.io/nginxdemos/hello:plain-text
    container_name: hello
    networks:
      - proxy
    environment:
      - HOSTNAME=${HOSTNAME}
    hostname: ${HOSTNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.hello-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hello-secure.entrypoints=https"
      - "traefik.http.routers.hello-secure.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.hello-secure.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.hello-secure.tls=true"
      - "traefik.http.routers.hello.middlewares=hello-https-redirect"
      - "traefik.http.routers.hello.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.services.hello.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  proxy:
    external: true
